version: '3.9'
services:
  ingestion:
    volumes:
      - ./:/app
      - models-cache:${MODELS_CACHE_PATH:-/var/cache/rag-models}
      - ./extensions:${EXTENSIONS_DIR:-/extensions}:ro
      - ./.cache:/app/.cache
    environment:
      UVICORN_RELOAD: '1'
    command: uvicorn services.ingestion.main:app --host 0.0.0.0 --port 8000 --reload
  processing:
    volumes:
      - ./:/app
      - models-cache:${MODELS_CACHE_PATH:-/var/cache/rag-models}
      - ./extensions:${EXTENSIONS_DIR:-/extensions}:ro
      - ./.cache:/app/.cache
    environment:
      UVICORN_RELOAD: '1'
    command: uvicorn services.processing.main:app --host 0.0.0.0 --port 8000 --reload
  testset:
    volumes:
      - ./:/app
      - models-cache:${MODELS_CACHE_PATH:-/var/cache/rag-models}
      - ./extensions:${EXTENSIONS_DIR:-/extensions}:ro
      - ./.cache:/app/.cache
    environment:
      UVICORN_RELOAD: '1'
    command: uvicorn services.testset.main:app --host 0.0.0.0 --port 8000 --reload
  eval:
    volumes:
      - ./:/app
      - models-cache:${MODELS_CACHE_PATH:-/var/cache/rag-models}
      - ./extensions:${EXTENSIONS_DIR:-/extensions}:ro
      - ./.cache:/app/.cache
    environment:
      UVICORN_RELOAD: '1'
    command: uvicorn services.eval.main:app --host 0.0.0.0 --port 8000 --reload
  reporting:
    volumes:
      - ./:/app
      - models-cache:${MODELS_CACHE_PATH:-/var/cache/rag-models}
      - ./extensions:${EXTENSIONS_DIR:-/extensions}:ro
      - ./.cache:/app/.cache
    environment:
      UVICORN_RELOAD: '1'
    command: uvicorn services.reporting.main:app --host 0.0.0.0 --port 8000 --reload
  adapter:
    volumes:
      - ./:/app
      - models-cache:${MODELS_CACHE_PATH:-/var/cache/rag-models}
      - ./extensions:${EXTENSIONS_DIR:-/extensions}:ro
      - ./.cache:/app/.cache
    environment:
      UVICORN_RELOAD: '1'
    command: uvicorn services.adapter.main:app --host 0.0.0.0 --port 8000 --reload
  kg:
    volumes:
      - ./:/app
      - models-cache:${MODELS_CACHE_PATH:-/var/cache/rag-models}
      - ./extensions:${EXTENSIONS_DIR:-/extensions}:ro
      - ./.cache:/app/.cache
    environment:
      UVICORN_RELOAD: '1'
    command: uvicorn services.kg.main:app --host 0.0.0.0 --port 8000 --reload
