# Test Configuration for Custom Document Processing
mode: 'local'

custom_data:
  enabled: true
  
  data_sources:
    text_files:
      - 'sample_documents/ai_machine_learning.txt'
      - 'sample_documents/cloud_computing.txt' 
      - 'sample_documents/cybersecurity.txt'
    
    directories:
      - 'sample_documents/'
  
  processing:
    chunk_size: 800
    chunk_overlap: 100
    min_chunk_size: 50
    remove_extra_whitespace: true
  
  topic_extraction:
    enabled: true
    method: 'keybert'
    max_topics_per_document: 4
  
  question_templates:
    - "What does the document explain about {}?"
    - "According to the text, what is {}?"
    - "How is {} described in the document?"
    - "What are the key aspects of {} mentioned?"

dataset:
  num_samples: 15
  output_file: 'test_custom_dataset.xlsx'

logging:
  level: 'INFO'
  show_progress: true
