# Domain-Specific RAG Evaluation Pipeline Configuration
# This config file controls all aspects of the hybrid evaluation pipeline

# ============================================================================
# PIPELINE SETTINGS
# ============================================================================
pipeline:
  name: "Redfish RAG Evaluation"
  version: "1.0.0"
  mode: "hybrid"  # Options: local, ragas, hybrid
  
# ============================================================================
# INPUT DATA SOURCES
# ============================================================================
data_sources:
  # Document directories and files to process
  documents:
    # Primary document source
    primary_docs:
      - "../../documents/DSP0266_1.22.0.pdf"
    
    # Additional document directories (optional)
    additional_dirs:
      - "../../sample_documents/"
    
    # File type filters
    file_types:
      - "pdf"
      - "docx" 
      - "txt"
      - "md"
    
    # Document processing settings
    processing:
      chunk_size: 256
      chunk_overlap: 25
      language: "en"
      min_doc_length: 50  # Skip docs smaller than this

# ============================================================================
# TESTSET GENERATION
# ============================================================================
testset_generation:
  # Number of QA pairs per document
  samples_per_document: 10
  
  # Maximum total samples (across all documents)
  max_total_samples: 10
  
  # Question generation strategies
  strategies:
    simple: 0.4       # 40% simple factual questions
    multi_context: 0.3 # 30% multi-context questions
    reasoning: 0.2    # 20% reasoning questions
    conditional: 0.1  # 10% conditional questions
  
  # Keyword extraction settings
  keyword_extraction:
    methods:
      - "keybert"     # Primary method
      - "yake"        # Fallback method
      - "spacy_ner"   # Named entity extraction
    
    min_keywords: 3
    max_keywords: 8
    
    # KeyBERT settings
    keybert:
      model: "all-MiniLM-L6-v2"
      keyphrase_ngram_range: [1, 2]
      stop_words: "english"
    
    # YAKE settings  
    yake:
      language: "en"
      max_ngram_size: 2
      deduplication_threshold: 0.7
  
  # Use RAGAS TestsetGenerator (if available)
  use_ragas_generator: true
  
  # RAGAS configuration with custom LLM support
  ragas_config:
    use_openai: false  # Disable OpenAI
    use_custom_llm: true  # Enable custom LLM
    
    # Custom LLM configuration
    custom_llm:
      endpoint: "http://llm-proxy.tao.inventec.net/v1/chat/completions"
      api_key_file: "config/secrets.yaml"  # Load API key from secrets file
      api_key_path: "inventec_llm.api_key"  # Path within secrets file
      model: "Qwen3-32B"
      
      # Request settings
      temperature: 0.3  # For question generation
      max_tokens: 1000
      stream: false
      
      # Optional custom headers
      headers:
        "Accept": "*/*"
        "Content-Type": "application/json"
        "User-Agent": "RAG-Evaluation-Pipeline/1.0"
    
    # Embeddings (always local for privacy)
    embeddings_model: "sentence-transformers/all-MiniLM-L6-v2"
  
  # Output settings
  output:
    format: "excel"  # Options: excel, csv, json
    include_metadata: true
    tag_source_files: true

# ============================================================================
# RAG SYSTEM INTERFACE
# ============================================================================
rag_system:
  # API endpoint for the RAG system to evaluate
  endpoint: "http://localhost:8080/query"
  
  # Authentication (if required)
  auth:
    type: "bearer"  # Options: none, bearer, api_key
    token: "${RAG_API_TOKEN}"  # Environment variable
  
  # Request settings
  timeout: 30
  max_retries: 3
  
  # Request format
  request_format:
    question_field: "question"
    response_fields:
      answer: "answer"
      contexts: "contexts"
      confidence: "confidence"

# ============================================================================
# EVALUATION METRICS
# ============================================================================
evaluation:
  # Contextual Keyword Gate Settings
  contextual_keywords:
    enabled: true
    weights:
      mandatory: 0.8
      optional: 0.2
    
    threshold: 0.6
    
    # Semantic similarity settings
    similarity_model: "all-MiniLM-L6-v2"
    
    # Context extraction settings
    spacy_model: "en_core_web_sm"
    
  # RAGAS Metrics Settings
  ragas_metrics:
    enabled: true
    
    # Metrics to compute
    metrics:
      - "context_precision"
      - "context_recall" 
      - "faithfulness"
      - "answer_relevancy"
    
    # LLM settings for RAGAS
    llm:
      use_local: true
      model_name: "microsoft/DialoGPT-medium"
      max_length: 512
      device: "auto"
    
    # Embedding settings for RAGAS
    embeddings:
      model_name: "all-MiniLM-L6-v2"
      
  # Dynamic Human Feedback Gate
  human_feedback:
    enabled: true
    
    # Initial threshold settings
    initial_threshold: 0.7
    
    # Uncertainty bounds for active learning
    uncertainty_bounds:
      min: 0.3
      max: 0.9
      buffer: 0.1
    
    # Feedback collection settings  
    diverse_sample_rate: 0.2
    recalibration_interval: 10
    
    # Threshold smoothing
    smoothing:
      alpha: 0.1  # Exponential smoothing factor
      min_window_size: 3
      max_window_size: 10
      consistency_threshold: 0.2

# ============================================================================
# REPORT GENERATION
# ============================================================================
reporting:
  # Report types to generate
  report_types:
    - "comprehensive"  # Full detailed report
    - "executive"      # High-level summary
    - "technical"      # Technical metrics
    - "comparative"    # Compare with baselines
  
  # Report formats
  formats:
    - "html"
    - "pdf" 
    - "excel"
    - "json"
  
  # Report sections
  sections:
    - "executive_summary"
    - "testset_overview"
    - "rag_performance_analysis"
    - "contextual_keyword_analysis"
    - "ragas_metrics_analysis"
    - "human_feedback_insights"
    - "question_type_breakdown"
    - "source_document_analysis"
    - "recommendations"
    - "methodology"
  
  # Visualization settings
  visualizations:
    enabled: true
    chart_types:
      - "performance_trends"
      - "score_distributions" 
      - "keyword_coverage_heatmap"
      - "question_difficulty_analysis"
      - "source_performance_comparison"
    
    style:
      theme: "professional"
      color_palette: "blues"

# ============================================================================
# OUTPUT SETTINGS
# ============================================================================
output:
  # Base output directory
  base_dir: "./outputs"
  
  # Timestamped subdirectories
  use_timestamps: true
  
  # File naming conventions
  naming:
    testset_prefix: "testset"
    report_prefix: "evaluation_report"
    metadata_prefix: "metadata"
  
  # Retention settings
  retention:
    keep_intermediate_files: true
    max_runs_to_keep: 10

# ============================================================================
# LOGGING & DEBUGGING
# ============================================================================
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  
  # Log destinations
  destinations:
    - "console"
    - "file"
  
  # File logging settings
  file_logging:
    log_file: "./outputs/logs/pipeline.log"
    max_size_mb: 100
    backup_count: 5
  
  # Performance monitoring
  performance:
    enabled: true
    track_memory: true
    track_timing: true

# ============================================================================
# ADVANCED SETTINGS
# ============================================================================
advanced:
  # Parallel processing
  parallelization:
    enabled: true
    max_workers: 4
    
  # Caching
  caching:
    enabled: true
    cache_dir: "./cache"
    cache_testsets: true
    cache_embeddings: true
    
  # Error handling
  error_handling:
    continue_on_error: true
    max_failures_per_document: 5
    
  # Resource limits
  resource_limits:
    max_memory_mb: 4096
    max_processing_time_minutes: 60

# ============================================================================
# ENVIRONMENT VARIABLES
# ============================================================================
# These can be overridden by environment variables:
# - RAG_API_TOKEN: Authentication token for RAG system
# - OPENAI_API_KEY: If using OpenAI models  
# - HF_TOKEN: Hugging Face token for model access
