# Secrets Configuration File
# This file contains sensitive API keys and credentials
# Add this file to .gitignore to keep secrets out of version control

# ============================================================================
# CUSTOM LLM API CONFIGURATION
# ============================================================================
inventec_llm:
  api_key: "sk-keyxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"  # Replace with your actual API key
  
# ============================================================================
# OTHER API KEYS (Optional - add as needed)
# ============================================================================
openai:
  api_key: ""  # Optional: OpenAI API key if you want to use OpenAI as fallback

# RAG System Authentication (if your RAG system requires auth)
rag_system:
  api_key: ""  # Optional: Your RAG system API key
  
# Other services (add as needed)
other_services:
  service_a_key: ""
  service_b_token: ""
