data_sources:
  documents:
    document_files:
      - "/data/yy/domain-specific-llm-eval/eval-pipeline/data/documents/document_0.txt"
      - "/data/yy/domain-specific-llm-eval/eval-pipeline/data/documents/document_1.txt"
      - "/data/yy/domain-specific-llm-eval/eval-pipeline/data/documents/document_2.txt"
      - "/data/yy/domain-specific-llm-eval/eval-pipeline/data/documents/document_3.txt"
      - "/data/yy/domain-specific-llm-eval/eval-pipeline/data/documents/document_4.txt"
      - "/data/yy/domain-specific-llm-eval/eval-pipeline/data/documents/document_5.txt"
      - "/data/yy/domain-specific-llm-eval/eval-pipeline/data/documents/document_6.txt"
      - "/data/yy/domain-specific-llm-eval/eval-pipeline/data/documents/document_7.txt"
      - "/data/yy/domain-specific-llm-eval/eval-pipeline/data/documents/document_8.txt"
      - "/data/yy/domain-specific-llm-eval/eval-pipeline/data/documents/document_9.txt"

testset_generation:
  max_total_samples: 10

output:
  base_dir: ./outputs
  use_timestamps: true

logging:
  level: INFO
