apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: reviewer-service
spec:
  podSelector:
    matchLabels:
      app: reviewer-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8010
  egress:
    - to:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53