thresholds:
  ContextPrecision:
    warning: 0.95
    critical: 0.90
  ContextRecall:
    warning: 0.95
    critical: 0.90
  Faithfulness:
    warning: 0.35
    critical: 0.30
  AnswerRelevancy:
    warning: 0.70
    critical: 0.60
